#!/bin/sh

set -e

export CGO_ENABLED=0
rm -rf /tmp/artifacts
mkdir -p /tmp/artifacts
go test -timeout 30s -coverprofile /tmp/artifacts/ut.cov ./...
go tool cover -html=/tmp/artifacts/ut.cov -o /tmp/artifacts/ut.html

set +e